language: node

node_js:
  - $TRAVIS_NODE_VERSION # uses .nvmrc as default

addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4

cache:
  yarn: true
  directories:
    - ~/.cache

before_install:
  # install yarn
  - npm install -g yarn@1.22.1

install: yarn install --frozen-lockfile


jobs:
  include:
    - stage: "Build"
      script: yarn client:build
    - stage: "Tests"
      script: yarn client:test
    - script: yarn server:test
    - script: yarn cy:test
