language: node
node_js:
  - $TRAVIS_NODE_VERSION # uses .nvmrc as default

before_install:
  # install yarn
  - npm install -g yarn

install: yarn install

cache:
  yarn: true

jobs:
  include:
    - stage: "Tests"
      script: yarn client:test
    -
      script: yarn server:test
    -
      script: yarn cy:test
    - stage: "Build"
      script: yarn client:build
